### ISSUE TITLE
login

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/MyWebSite#3]
in attesa ...

**Comment by LuigiVessella** [comment]
Fatto

**Comment by FabioZTessitore** [comment]
guarda l'ultimo rigo

**Comment by LuigiVessella** [comment]
Cosa non va?

**Comment by FabioZTessitore** [comment]
ti ho chiesto di guardare. devi dirmi tu cosa non va

**Comment by LuigiVessella** [comment]
Così?

Il 26 gen 2017 15:54, "Fabio Z Tessitore" <notifications@github.com> ha
scritto:

**Comment by FabioZTessitore** [comment]
Quella secondo te è l'ultima riga?

**Comment by LuigiVessella** [comment]
L'ultima è </html>


2017-01-26 16:24 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
e controllala

**Comment by LuigiVessella** [comment]
cosa c'è che non va? l'ho controllata

2017-01-26 16:27 GMT+01:00 Fabio Z Tessitore <notifications@github.com>:

**Comment by FabioZTessitore** [comment]
controlla quello che hai messo su github

**Comment by LuigiVessella** [comment]
ahhh ahaha prof cosa vi ha fatto di male quella 'a'..
Non l'avevo vista proprio dal telefono..Fatto
